### ISSUE TITLE
Regarding new xsl files

### ISSUE THREAD

**Issue by mandavavinay** [stephenjust/fastmath#1]
Hi, 

When I see your code you are referring to files in folder "MathServer/xslt" but, when i download your code  I don't see these files at  /srv/http/fastmath/MathServer/ folder. So, can you put the new modified files.

Thanks,

**Comment by stephenjust** [comment]
The location of the xsl files was hard-coded to an incorrect directory. I will remove the hard-coding. In the meantime, the xsl directory in your copy of the source can simply be copied to the appropriate location.

**Comment by stephenjust** [comment]
It looks like the entire MathServer directory was from an old version of the code. It has been completely removed. Its replacement (fm.mathengine) already properly located the xsl files.

**Comment by mandavavinay** [comment]
But the existing xls files are not converting MathML to SymPy
understandably format right. They are converting to LaTex.

On Wed, Mar 25, 2015 at 8:42 PM, Stephen Just notifications@github.com
wrote:

> Closed #1 https://github.com/stephenjust/fastmath/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stephenjust/fastmath/issues/1#event-264825292.

## 

Vinay Mandava
91-9885127836

**Comment by stephenjust** [comment]
Ah, the XSLT files were originally for a MathML to LaTeX  conversion, but they are partially modified to handle the conversion to something understandable by SymPy.

The transform to SymPy only works for a small subset of MathML - only the parts needed to actually submit answers to the questions generated by the fastmath application.

**Comment by mandavavinay** [comment]
Thanks alot for the information.

On Wed, Mar 25, 2015 at 8:57 PM, Stephen Just notifications@github.com
wrote:

> Ah, the XSLT files were originally for a MathML to LaTeX conversion, but
> they are partially modified to handle the conversion to something
> understandable by SymPy.
> 
> The transform to SymPy only works for a small subset of MathML - only the
> parts needed to actually submit answers to the questions generated by the
> fastmath application.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stephenjust/fastmath/issues/1#issuecomment-86081793.

## 

Vinay Mandava
91-9885127836
